---
#- name: gather facts
#  onyx_facts:
#    gather_subset: all
- name: reset factory
  onyx_config:
     lines:
        - no cli default prompt confirm-reset
        - reset factory
  register: output
  ignore_errors: yes


#- name: pause_wait_for_device_to_finish_reset_factory
#  pause:
#    minutes: "{{pause_after_reset | default(0) }}"
