---
- name: get_facts_from_device
  onyx_facts:
    gather_subset: version
- name: image boot next and reload
  onyx_config:
      lines:
        - image boot next
        - configuration write
        - no boot next fallback-reboot enable
        - reload
      backup: no
      save: yes
  when:  ansible_net_version['Product release']  != version
  ignore_errors: yes
