---
- name: get_facts_from_device
  onyx_facts:
    gather_subset: version

- name: image fetch
  onyx_command:
     commands: image fetch scp://{{ user }}:{{ password }}@{{remote_ip }}:{{ path }}/image-{{ cpu }}-{{ version }}.img
  when:  ansible_net_version['Product release']  != version
  tags:
      - fetch
- name: image install
  onyx_command:
     commands: image install image-{{ cpu }}-{{ version }}.img
  tags:
    - install
  when:  ansible_net_version['Product release']  != version
